### PR TITLE
Merge changes for version 2.0(?)

### PR DESCRIPTION
**Pull request by tmelliott**

### CODE REVIEW

**Comment by tmelliott** [comment]
@daniel-barnett is the `support-R32` branch necessary?

**Comment by tmelliott** [comment]
Last two commits seem to get past the travis-specific issues - remaining are coming from R package check.

<details>
<summary>R CMD check log</summary>

```r
Checking with: R CMD check iNZightMaps_2.0-0.tar.gz --as-cran --no-manual --no-manual --no-manual --no-manual --no-manual --no-manual --no-manual --no-manual --no-manual --no-manual
55.20s$ R CMD check "${PKG_TARBALL}" --as-cran --no-manual --no-manual --no-manual --no-manual --no-manual --no-manual --no-manual --no-manual --no-manual --no-manual; CHECK_RET=$?
* using log directory ‘/home/travis/build/iNZightVIT/iNZightMaps/iNZightMaps.Rcheck’
* using R version 3.5.0 (2017-01-27)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* using options ‘--no-manual --as-cran’
* checking for file ‘iNZightMaps/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘iNZightMaps’ version ‘2.0-0’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking serialization versions ... OK
* checking whether package ‘iNZightMaps’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... WARNING
plot:
  function(x, ...)
plot.iNZightMapPlot:
  function(obj, colour.var, size.var, alpha.var, fill.const,
           colour.const, size.const, alpha.const, facet, multiple.vars,
           main, xlab, ylab, axis.labels, datum.lines, darkTheme,
           projection, palette, label.title, aggregate, current.seq,
           sparkline.type, scale.limits, ci.plot, regions.to.plot,
           keep.other.regions, label.var, scale.label, scale.axis)
plot:
  function(x, ...)
plot.inzmap:
  function(obj, gen)
plot:
  function(x, ...)
plot.inzshapemap:
  function(obj, gen)
See section ‘Generic functions and methods’ in the ‘Writing R
Extensions’ manual.
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... NOTE
drawing.features: warning in grid.polygon(bar.obj$d1[, 1], bar.obj$d1[,
  2], default.units = "native", id.length = bar.obj$each, gp = gpar(col
  = NA, fill = bar.obj$col)): partial argument match of 'id.length' to
  'id.lengths'
drawing.features: warning in grid.text(out.str, x = center.x, y =
  center.y, just = "centre", default.units = "native", gp =
  gpar(fontsize = 9), check = TRUE): partial argument match of 'check'
  to 'check.overlap'
plot.inzshapemap: warning in grid.polygon(latlon[, 1], latlon[, 2],
  default.units = "native", id.length = shade.each, gp = gpar(col =
  "#B29980", fill = cols)): partial argument match of 'id.length' to
  'id.lengths'
sClickOnZoom: warning in grid.polygon(s.obj$latlon[, 1], s.obj$latlon[,
  2], default.units = "native", id.length = s.obj$each, gp = gpar(col =
  "#B29980", fill = s.obj$col)): partial argument match of 'id.length'
  to 'id.lengths'
ClickOnZoom: no visible binding for global variable ‘global.objects’
ClickOnZoom: no visible binding for '<<-' assignment to
  ‘global.objects’
col.fun: no visible global function definition for ‘hcl’
col.fun: no visible global function definition for ‘col2rgb’
col.fun: no visible global function definition for ‘rgb’
col.fun: no visible global function definition for ‘heat.colors’
col.fun: no visible global function definition for ‘rainbow’
col.fun: no visible global function definition for ‘terrain.colors’
col.fun: no visible global function definition for ‘topo.colors’
col.fun: no visible global function definition for ‘cm.colors’
col.fun: no visible global function definition for ‘gray’
col.fun: no visible global function definition for ‘runif’
data.trans: no visible global function definition for ‘dnorm’
download.shapefiles: no visible global function definition for
  ‘download.file’
Get.map.size: no visible binding for global variable ‘global.objects’
getNewMap: no visible binding for '<<-' assignment to ‘map’
getNewMap: no visible binding for global variable ‘map’
iNZightMapAggregation: no visible global function definition for ‘UQ’
iNZightMapAggregation: no visible binding for global variable ‘.’
iNZightMapPlotRegion: no visible global function definition for ‘UQ’
iNZightShapeMap: no visible binding for '<<-' assignment to ‘bar.obj’
plot.iNZightMapPlot: no visible global function definition for
  ‘dev.size’
plot.iNZightMapPlot: no visible global function definition for
  ‘n2mfrow’
plot.iNZightMapPlot: no visible global function definition for ‘:=’
plot.iNZightMapPlot: no visible global function definition for ‘UQ’
plot.iNZightMapPlot: no visible global function definition for
  ‘st_transform’
plot.iNZightMapPlot: no visible global function definition for
  ‘na.omit’
plot.inzightshapemap: no visible global function definition for ‘sd’
plot.inzightshapemap: no visible global function definition for ‘dnorm’
plot.inzightshapemap: no visible global function definition for
  ‘modifyList’
plot.inzmap: no visible binding for global variable ‘global.objects’
plot.inzmap: no visible binding for '<<-' assignment to
  ‘global.objects’
plot.inzshapemap: no visible binding for global variable ‘bar.obj’
plot.inzshapemap: no visible binding for '<<-' assignment to
  ‘inzshpobj’
read.mapmetadata: no visible global function definition for
  ‘download.file’
read.mapmetadata : <anonymous>: no visible global function definition
  for ‘error’
sClickOnZoom: no visible binding for global variable ‘inzshpobj’
sClickOnZoom: no visible binding for '<<-' assignment to ‘inzshpobj’
shape.extract: no visible global function definition for ‘coordinates’
shape.extract: no visible global function definition for ‘slot’
shape.extract: no visible binding for global variable ‘slot’
Undefined global functions or variables:
  := . bar.obj cm.colors col2rgb coordinates dev.size dnorm
  download.file error global.objects gray hcl heat.colors inzshpobj map
  modifyList n2mfrow na.omit rainbow rgb runif sd slot st_transform
  terrain.colors topo.colors UQ
Consider adding
  importFrom("grDevices", "cm.colors", "col2rgb", "dev.size", "gray",
             "hcl", "heat.colors", "n2mfrow", "rainbow", "rgb",
             "terrain.colors", "topo.colors")
  importFrom("methods", "slot")
  importFrom("stats", "dnorm", "na.omit", "runif", "sd")
  importFrom("utils", "download.file", "modifyList")
to your NAMESPACE file (and ensure that your DESCRIPTION Imports field
contains 'methods').
Found the following assignments to the global environment:
File ‘iNZightMaps/R/general.R’:
  assign("global.objects", global.objects, envir = .GlobalEnv)
  assign("global.objects", global.objects, envir = .GlobalEnv)
File ‘iNZightMaps/R/inzmap.R’:
  assign("global.objects", list(), envir = .GlobalEnv)
* checking Rd files ... WARNING
checkRd: (5) create.inz.mapplot.Rd:0-18: Must have a \description
checkRd: (5) iNZightMapAggregation.Rd:0-16: Must have a \description
checkRd: (5) iNZightMapPlot.Rd:0-43: Must have a \description
checkRd: (5) iNZightMapVars.Rd:0-14: Must have a \description
checkRd: (5) retrieveMap.Rd:0-15: Must have a \description
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... WARNING
Undocumented code objects:
  ‘decodeMapDir’ ‘download.shapefiles’ ‘getMinMax’
  ‘iNZightMapCountryISO’ ‘iNZightMapProjections’ ‘iNZightMapRegions’
  ‘read.mapmetadata’
All user-level objects in a package should have documentation entries.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
* checking for code/documentation mismatches ... WARNING
Data codoc mismatches from documentation object 'nzquakes':
Variables in data frame 'nzquakes'
  Code: Day Depth Felt Hour Latitude Longitude Magnitude Minute Month
        NorMidSth Order RMS
  Docs: Latitude Longitude Order
* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'ClickOnZoom'
  ‘resize’ ‘p.center’
Undocumented arguments in documentation object 'data.trans'
  ‘data.range’ ‘mean’ ‘sd’ ‘max.prob’
Undocumented arguments in documentation object 'drawing.features'
  ‘data.region’
Undocumented arguments in documentation object 'findBestMatch'
  ‘data’ ‘map.data’
Undocumented arguments in documentation object 'getNewMap'
  ‘type’
Documented arguments not in \usage in documentation object 'getNewMap':
  ‘variable’
Undocumented arguments in documentation object 'iNZightMap'
  ‘env’
Duplicated \argument entries in documentation object 'iNZightMapPlot':
  ‘data’ ‘map’
Documented arguments not in \usage in documentation object 'iNZightShapeMap':
  ‘the’
Undocumented arguments in documentation object 'name.match'
  ‘shp.region’ ‘data.region’
Documented arguments not in \usage in documentation object 'name.match':
  ‘obj’
Undocumented arguments in documentation object 'needNewMap'
  ‘size’
Documented arguments not in \usage in documentation object 'needNewMap':
  ‘sized’
Undocumented arguments in documentation object 'plot.iNZightMapPlot'
  ‘alpha.var’ ‘fill.const’ ‘colour.const’ ‘facet’ ‘label.title’
  ‘ci.plot’ ‘regions.to.plot’ ‘keep.other.regions’ ‘label.var’
  ‘scale.label’ ‘scale.axis’
Undocumented arguments in documentation object 'plot.inzightshapemap'
  ‘variable’ ‘transform’ ‘col.offset’ ‘col’ ‘na.fill’ ‘extend.ratio’
  ‘name’ ‘zoom’ ‘zoom.center’ ‘...’
Documented arguments not in \usage in documentation object 'plot.inzightshapemap':
  ‘variablie’ ‘region’ ‘data’
Undocumented arguments in documentation object 'sClickOnZoom'
  ‘resize’
Undocumented arguments in documentation object 'shape.extract'
  ‘column.index’
Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of ‘data’ directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking R/sysdata.rda ... OK
* checking examples ... NONE
* DONE
```

</details>

**Comment by daniel-barnett** [comment]
Nope, the support-R32 branch shouldn't be necessary

**Comment by tmelliott** [comment]
Will use a release branch PR instead

**Comment by daniel-barnett** [comment]
I'll go through the package check stuff and fix some of the documentation, etc soon if you like?

**Comment by tmelliott** [comment]
I've started on `feature/pass-cran-checks` branch. If you can pull that and see what you can fix, that'd be great.

**Pull request closed without merging**
