### PR TITLE
Dot density maps

### PR DESCRIPTION
**Pull request by daniel-barnett**

### CODE REVIEW

**Comment by tmelliott** [comment]
Docs need updating @daniel-barnett

**Comment by daniel-barnett** [comment]
Sorry, should be fixed now?

**Comment by tmelliott** [comment]
R-devel has added a new check. Fix should be to add "LazyData: true" to the DESCRIPTION file (e.g., https://github.com/iNZightVIT/iNZight/blob/dev/DESCRIPTION#L50).

**Comment by daniel-barnett** [comment]
Should be OK once Travis does its thing, but we'll see.

**Pull request merged**
